# Generated by Django 2.2.1 on 2019-08-19 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FbFeedService', '0002_auto_20190808_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='full_text',
            field=models.CharField(max_length=8191),
        ),
        migrations.AlterField(
            model_name='feed',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
