# Generated by Django 2.2.1 on 2019-08-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FbFeedService', '0003_increase_feedid_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='comment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='feed',
            name='crawled_dt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='share_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='feed',
            name='post_dt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
