# Generated by Django 2.2.1 on 2019-08-21 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FbFeedService', '0005_auto_20190819_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('feedID', models.BigIntegerField(default=0)),
            ],
        ),
    ]
