# Generated by Django 2.2.1 on 2019-08-26 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FbFeedService', '0006_added_hashtag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=255)),
                ('ads', models.BooleanField(default=True)),
                ('page_created_date', models.DateField()),
                ('total_number_of_manager', models.IntegerField(default=0)),
                ('manager', models.CharField(max_length=511)),
            ],
        ),
    ]
