# Generated by Django 2.2.1 on 2019-08-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FbFeedService', '0007_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='IGPost',
            fields=[
                ('id', models.CharField(max_length=31, primary_key=True, serialize=False)),
                ('full_text', models.CharField(max_length=8191)),
                ('author_name', models.CharField(max_length=255)),
                ('crawled_dt', models.DateTimeField()),
                ('post_dt', models.DateTimeField()),
                ('like', models.IntegerField(default=0)),
                ('comment', models.IntegerField(default=0)),
            ],
        ),
    ]
