# Generated by Django 2.2.1 on 2019-09-10 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IgFeedService', '0002_auto_20190910_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='number_of_post',
            new_name='posts',
        ),
    ]
